name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle 8.10.2
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
          gradle-version: "8.10.2"

      - name: Build All
        run: gradle build
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: VoxelCraft Desktop
          path: /home/runner/work/VoxelCraft/VoxelCraft/desktop/build/libs
          overwrite: true
          retention-days: 7

      - uses: actions/upload-artifact@v4
        with:
            name: VoxelCraft Server
            path: /home/runner/work/VoxelCraft/VoxelCraft/server/build/libs
            overwrite: true
            retention-days: 7
