name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle 8.10.2
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
          gradle-version: "8.10.2"

      - name: Build Desktop
        run: gradle build :desktop:publish
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Server
        run: gradle build :server:publish
        env:
          USER: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
